name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install Azure ML SDK
      run: |
        python -m pip install --upgrade pip
        pip install azureml-core azureml-sdk
        
    - name: Download CSV from Azure Blob Storage
      run: |
        az storage blob download \
          --container-name gamer \
          --name gamer \
          --file candidate_information.csv \
          --connection-string ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        if [ $? -eq 0 ]; then
          echo "CSV file downloaded successfully."
        else
          echo "Failed to download CSV file."
          exit 1
        fi

    - name: Train Model
      run: python train.py

    - name: Evaluate Model
      run: python evaluate.py

    - name: Deploy Model
      run: python deploy.py
