name: My Workflow
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn joblib
        pip install azureml-core scikit-learn pandas numpy
        
    - name: Download CSV from GitHub
      run: |
        wget https://raw.githubusercontent.com/Disciplined-22/dev_ml_csalary_01/main/candidate_information.csv -O candidate_information.csv
      
    - name: Evaluate Model
      run: python evaluate.py

    - name: Deploy Model
      run: python deploy.py
